version: "3"
services:
  app:
    build: .
    ports:
      - "8069:8069"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
