version: "3"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  redis_data:
